const form=document.querySelector('#briefForm'),steps=[...document.querySelectorAll('.step')],next=document.querySelector('#next'),back=document.querySelector('#back'),submit=document.querySelector('#submit'),error=document.querySelector('#error');let current=0;const key='ammar-website-brief-v1';
const fields=()=>[...form.elements].filter(x=>x.name&&!x.classList.contains('trap'));
function save(){const data={};fields().forEach(x=>{if(x.type==='checkbox'){data[x.name]=data[x.name]||[];if(x.checked)data[x.name].push(x.value)}else if(x.type==='radio'){if(x.checked)data[x.name]=x.value}else data[x.name]=x.value});localStorage.setItem(key,JSON.stringify(data))}
function restore(){try{const data=JSON.parse(localStorage.getItem(key)||'{}');fields().forEach(x=>{if(x.type==='checkbox')x.checked=(data[x.name]||[]).includes(x.value);else if(x.type==='radio')x.checked=data[x.name]===x.value;else if(data[x.name]!=null)x.value=data[x.name]})}catch{}}
function validate(){error.textContent='';let ok=true;steps[current].querySelectorAll('[required]').forEach(x=>{x.classList.remove('invalid');if(!x.checkValidity()){x.classList.add('invalid');ok=false}});steps[current].querySelectorAll('[data-required]').forEach(g=>{if(!g.querySelector('input:checked'))ok=false});if(!ok)error.textContent='Please complete the required fields before continuing.';return ok}
function review(){const data=new FormData(form),labels={businessName:'Business',industry:'Industry',projectType:'Project',platform:'Platform',primaryGoal:'Primary goal',pages:'Pages',features:'Features',designStyle:'Design style',budget:'Budget',timeline:'Timeline',email:'Email'};document.querySelector('#review').innerHTML=Object.entries(labels).map(([k,l])=>{const values=data.getAll(k).filter(Boolean);return values.length?`<div class="review-row"><small>${l}</small><strong>${values.join(', ')}</strong></div>`:''}).join('')}
function show(index){current=index;steps.forEach((s,i)=>s.classList.toggle('active',i===current));const total=steps.length,p=Math.round((current+1)/total*100);document.querySelector('#stepLabel').textContent=`STEP ${current+1} OF ${total}`;document.querySelector('#stepTitle').textContent=steps[current].dataset.title;document.querySelector('#percent').textContent=p+'%';document.querySelector('#progressBar').style.width=p+'%';back.style.visibility=current?'visible':'hidden';next.style.display=current===total-1?'none':'block';submit.style.display=current===total-1?'block':'none';if(current===total-1)review();error.textContent='';scrollTo({top:0,behavior:'smooth'})}
next.onclick=()=>{if(validate()){save();show(current+1)}};back.onclick=()=>show(Math.max(0,current-1));form.addEventListener('input',save);
form.onsubmit=async e=>{e.preventDefault();if(!validate())return;submit.disabled=true;submit.textContent='Sending…';try{const body=Object.fromEntries(new FormData(form));body.pages=new FormData(form).getAll('pages');const response=await fetch('/api/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw Error(result.error||'Submission failed');localStorage.removeItem(key);document.querySelector('#reference').textContent='Reference: '+result.reference;document.querySelector('#success').showModal();form.reset();show(0)}catch(err){error.textContent=err.message+'. Please try again.'}finally{submit.disabled=false;submit.innerHTML='Send my brief <b>→</b>'}};restore();show(0);
